<template>
    <div class="table-page grid grid-cols-[55%_44%] grid-rows-[max-content_1fr] gap-[10px] p-[5px]">
        <div class="slice-table grid gap-[2px] h-max col-[1/2] row-[1/2]">
            <div class="action-btns flex items-center justify-between">
                <div class="flex items-center justify-center gap-[2px]">
                    <Button
                        v-for="(btn, index) in angleBtn"
                        :key="btn"
                        :text="btn"
                        @on-click="sliceTableDisplay(index)"
                    />
                </div>
                <div class="flex items-center justify-center gap-[2px]">
                    <Button
                        v-for="(btn, index) in angleBtn2"
                        :key="btn"
                        :text="btn"
                        @on-click="sliceTableDisplay(index)"
                    />
                </div>
            </div>
            <span class="text-[12px]">slices:</span>
            <div class="slices-btns flex items-center gap-[1px]">
                <Button
                    v-for="(btn, index) in slices"
                    :key="btn"
                    :text="btn"
                    @on-click="sliceTableDisplay(index)"
                />
            </div>
            <div class="overflow-auto">
                <Table
                v-show="sliceTableNum % 2 === 0"
                :headers="sliceTable1.headers"
                :data="sliceTableData"
            />
            <Table
                v-show="sliceTableNum % 2 !== 0"
                :headers="sliceTable2.headers"
                :data="sliceTableData2"
            />
            </div>
        </div>
        <div class="coordinate3D-table overflow-auto col-[2/3] row-[1/3]">
            <Table
                :headers="coordinate3D.headers"
                :data="coordinate3D.data"
            />
        </div>
        <div class="deviation-table overflow-auto col-[1/2] rows-[2/3]">
            <Table
                :headers="deviation.headers"
                :data="deviation.data"
            />
        </div>
    </div>
</template>

<script>
import Button from "../components/Button.vue";
import Table from "../components/Table.vue";
export default {
    components: {
        Button,
        Table,
    },
    computed: {
        sliceTableData() {
            return [
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
            ];
        },
        sliceTableData2() {
            return [
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
                [
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                    Math.random().toFixed(3),
                ],
            ];
        },
    },
    data() {
        return {
            sliceTableNum: 1,
            angleBtn: ["axial(xy)", "coronal(xz)", "segital(yz)", "statistics"],
            angleBtn2: ["dx", "dy", "dz", "dr"],
            slices: [
                "30",
                "40",
                "50",
                "60",
                "70",
                "80",
                "90",
                "100",
                "110",
                "120",
                "130",
                "140",
                "150",
                "160",
            ],
            sliceTable1: {
                headers: [],
                data: this.sliceTableData,
            },
            sliceTable2: {
                headers: [],
                data: this.sliceTableData2,
            },
            coordinate3D: {
                headers: [
                    {
                        name: "x",
                        label: "x(mm)",
                    },
                    {
                        name: "y",
                        label: "y(mm)",
                    },
                    {
                        name: "z",
                        label: "z(mm)",
                    },
                    {
                        name: "x",
                        label: "x(mm)",
                    },
                    {
                        name: "y",
                        label: "y(mm)",
                    },
                    {
                        name: "z",
                        label: "z(mm)",
                    },
                    {
                        name: "x",
                        label: "x(mm)",
                    },
                    {
                        name: "y",
                        label: "y(mm)",
                    },
                    {
                        name: "z",
                        label: "z(mm)",
                    },
                    {
                        name: "x",
                        label: "x(mm)",
                    },
                    {
                        name: "y",
                        label: "y(mm)",
                    },
                    {
                        name: "z",
                        label: "z(mm)",
                    },
                ],
                data:[
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        Math.round(Math.random() * 100),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                ]
            },
            deviation: {
                headers: [
                    {
                        name: "",
                        label: "",
                    },
                    {
                        name: "dx",
                        label: "dx",
                    },
                    {
                        name: "dy",
                        label: "dy",
                    },
                    {
                        name: "dz",
                        label: "dz",
                    },
                    {
                        name: "dz",
                        label: "dz",
                    },
                ],
                data: [
                    [
                        'Maximum Absolure Deviation(mm)',
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        'Minimum Absolure Deviation(mm)',
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        'Mean Absolure Deviation(mm)',
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        'Standard Absolure Deviation(mm)',
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        'Maximum Absolure Cordinate(mm)',
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        'Minimum Absolure Cordinate(mm)',
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                    [
                        'Mean Absolure Cordinate(mm)',
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                        (Math.random() * 100).toFixed(3),
                    ],
                ]
            }
        };
    },
    methods: {
        sliceTableDisplay(index) {
            this.sliceTableNum = index;
        },
    },
    mounted() {
        console.log(this.sliceTableNum % 2 === 0);
        console.log(this.sliceTableNum % 2 !== 0);
    },
};
</script>
